"""initial migration

Revision ID: 8b4dd8d9f251
Revises: 
Create Date: 2024-04-05 19:01:52.292716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b4dd8d9f251'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('_password_hash', sa.String(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('artwork_path', sa.String(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_updated', sa.TIMESTAMP(), nullable=True),
    sa.CheckConstraint('(parent_id IS NULL AND title IS NOT NULL AND artwork_path IS NOT NULL) OR (parent_id IS NOT NULL AND title IS NULL AND body IS NOT NULL)', name='check_post_or_comment'),
    sa.ForeignKeyConstraint(['parent_id'], ['entities.id'], name=op.f('fk_entities_parent_id_entities')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_entities_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('follows',
    sa.Column('following_user_id', sa.Integer(), nullable=False),
    sa.Column('followed_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['followed_user_id'], ['users.id'], name=op.f('fk_follows_followed_user_id_users')),
    sa.ForeignKeyConstraint(['following_user_id'], ['users.id'], name=op.f('fk_follows_following_user_id_users')),
    sa.PrimaryKeyConstraint('following_user_id', 'followed_user_id')
    )
    op.create_table('likes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], name=op.f('fk_likes_entity_id_entities')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_likes_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'entity_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('likes')
    op.drop_table('follows')
    op.drop_table('entities')
    op.drop_table('users')
    # ### end Alembic commands ###
